#!/bin/bash -l

#SBATCH --job-name="poisson_mpi"
#SBATCH --account="project"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=64
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --account=uzh8
#SBATCH --output=output.log
#SBATCH --error=error.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun ./poisson
