#!/bin/bash -l

#SBATCH --job-name="omp_poisson"
#SBATCH --account="project"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --account=uzh8
#SBATCH --output=omp_output.log
#SBATCH --error=omp_error.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./omp_poisson
